# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Opinionated code formatter to forget about formatting
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black

  # Lint code to catch easy bugs and problems
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

  # Sort imports deterministically
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort